IF NOT EXISTS (SELECT 1 From INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'NeuralNetworkModel')
BEGIN
	CREATE TABLE NeuralNetworkModel (
		ID_Model INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
		ModelName NVARCHAR(255) NOT NULL,
		InputSize INT NOT NULL,
		HiddenSize INT NOT NULL,
		OutputSize INT NOT NULL,
		W1 NVARCHAR(MAX) NOT NULL,
		b1 NVARCHAR(MAX) NOT NULL,
		W2 NVARCHAR(MAX) NOT NULL,
		b2 NVARCHAR(MAX) NOT NULL,
		LastUpdated DATETIME NOT NULL DEFAULT GETDATE()
	);
END

GO
