IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SystemUser')
BEGIN
	CREATE TABLE dbo.SystemUser(
		ID_SystemUser INT IDENTITY (1,1) NOT NULL,
		UserName NVARCHAR(50) NOT NULL
	)
END
GO