IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME like 'TrainingData')
BEGIN
	CREATE TABLE TrainingData (
		ID_TrainingData INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
		Input VARCHAR(512) NOT NULL,
		DataLabel CHAR(1) NOT NULL,
		LastUpdated DATETIME NOT NULL DEFAULT GETDATE()
		);
END
GO